platform :ios, '9.0'
use_frameworks!

target 'Example' do

pod 'AXLoadingView',   :path => '..'

end



#pod install --verbose --no-repo-update      #安装命令
#pod update --verbose --no-repo-update       #更新命令
